### ISSUE TITLE
0.2.x roadmap

### ISSUE THREAD

**Issue by dandelany** [spotify/reactochart#3]
Work has begun on v0.2.0 and will be tracked in the `0.2.x` branch. Main objectives are:
- Improved label layout features and speed due to better pre-emptive label measuring.
- More modularization of component structure - export parts of charts, not just entire charts, so the parts can be composed individually.
- Encapsulation of reusable and extractable Component features using higher-order components. Not just for DRY-ness, but to make the Components themselves as simple as possible.

The feature roadmap will be tracked in this checklist, which we'll add to and edit as we go along:
- [x] Refactor mouse events on new XYPlot component
- [x] Production build of examples sandbox, for performance testing
- [x] Port existing charts to new XYPlot format (see below)
- [x] `Bar` component
- [x] `RangeRect` component
- [x] Use class-type components instead of `createClass`
- [x] `resolveXYScales` HOC to resolve scale prop from domain/range/data/size/etc.
- [x] `resolveObjectProps` HOC to handle setting default props for `{x,y}` and `{top, bottom, left, right}` shaped props
- [x] Use [`measure-text`](https://www.npmjs.com/package/measure-text) to pre-measure labels
- [x] `XAxis` and `YAxis` components
- [x] Unit test which renders the examples
- [x] Update `lodash` to 4.5.x
- [x] Add `babel` plugin for ESNext class properties
- [x] Axis label placement - see AUDINP-232

**Comment by dandelany** [comment]
## API changes

* `axisType` --> `scaleType`

**Comment by dandelany** [comment]
### Future plans (out of scope for 0.2.x)

* Rotated axis value labels
* Y axis value label vertical alignment (top/middle/bottom)
* `extraMargin`/`minMargin` props?
* `position: 'zero'` option for X/Y Axis and subcomponents - place the axis on the scale's zero line, wherever it falls.

**Comment by dandelany** [comment]
### Progress porting existing charts to 0.2.x/XYPlot2

* [ ] AreaHeatmap
* [ ] BarChart
* [ ] Histogram
* [ ] KernelDensityEstimation
* [ ] LineChart
* [ ] MarkerLineChart
* [ ] ScatterPlot

**Comment by dandelany** [comment]
### Future plans (out of scope for 0.2.x)

* [ ] PureRender/shouldComponentUpdate for all chart/axis components
* [ ] Automatically determine axis tickCount (and therefore # of axis labels) by bumping down the # of ticks until all of the labels fit
* [ ] Rotated axis value labels (90 degrees or arbitrary rotation? how to handle collision detection?)
* [ ] Y Axis value label vertical & horizontal alignment
* [ ] `position: 'zero'` option for X/Y Axis and subcomponents - place the axis on the scale's zero line, wherever it falls.
* [ ] `extraMargin`/`minMargin` props?

**Comment by cloudonshore** [comment]
@dandelany 
Did `labelFormat` get dropped when `xAxis` and `yAxis` got broken out from `XYPlot`? I see it in the `propTypes` but it doesn't look like it ever gets used.

**Comment by dandelany** [comment]
This is old - 0.2.0 and 0.3.0 have been released. Will open new tickets for remaining outstanding issues for future releases.
